export const SET_BOTS_LIST = 'SET_BOTS_LIST';
export const LOG_IN_ERROR = 'LOG_IN_ERROR';


export const DELETE_BOT = 'DELETE_BOT';
export const UPDATE_BOT = 'UPDATE_BOT';


export const OPEN_CLOSE_MODAL = 'OPEN_CLOSE_MODAL';



export const SHOW_CREATE_NEW_POST_FORM = 'SHOW_CREATE_NEW_POST_FORM';
export const SHOW_LANG_DROPDOWN = 'SHOW_LANG_DROPDOWN';

export const LANG_TERM_CHANGE_FORM = 'LANG_TERM_CHANGE_FORM';
export const SELECT_LANGUAGE_FORM = 'SELECT_LANGUAGE_FORM';
export const CLEAN_UP_FORM = 'CLEAN_UP_FORM';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';

export const SHOW_SUCCESS_POPUP = 'SHOW_SUCCESS_POPUP';



// export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const SET_UPLOADED_FILES = 'SET_UPLOADED_FILES';




export const OPEN_CLOSE_SETTINGS_LANG_DROPDOWN = 'OPEN_CLOSE_SETTINGS_LANG_DROPDOWN';



export const LANG_TERM_CHANGE = 'LANG_TERM_CHANGE';
export const SELECT_LANGUAGE = 'SELECT_LANGUAGE';
export const CLEAN_UP = 'CLEAN_UP';


export const SET_NEW_BOT = 'SET_NEW_BOT';


